# Generated by Django 4.0.3 on 2022-03-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_entregableprofesor_estudiantes_profesor'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Entregable',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
    #             ('fecha', models.DateField(max_length=50, verbose_name='fecha')),
    #             ('entregado', models.BooleanField()),
    #         ],
    #     ),
    #     migrations.DeleteModel(
    #         name='EntregableProfesor',
    #     ),
    # ]
