# Generated by Django 4.0.3 on 2022-03-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_familia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntregableProfesor',
            new_name='Entregable',
        ),
    ]
